Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ck.Data;
using ck.Models;
using Microsoft.AspNetCore.Authorization;

namespace ck.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ckContext _context;

        public MoviesController(ckContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Genre(int id)
        {
            var moviesByGenre = await _context.Movie
                .Include(m => m.genre)
                .Where(m => m.GenreId == id)
                .ToListAsync();

            var genreName = await _context.Genre
                .Where(g => g.Id == id)
                .Select(g => g.Name)
                .FirstOrDefaultAsync();

            ViewBag.GenreName = genreName;
            return View("MoviesByGenre", moviesByGenre);
        }
        [HttpGet]
        public async Task<IActionResult> Search(string? query)
        {
            if (string.IsNullOrEmpty(query))
            {
                // Nếu không nhập gì thì trả lại toàn bộ danh sách
                var allMovies = await _context.Movie.Include(m => m.genre).ToListAsync();
                return View("Index", allMovies);
            }

            var result = await _context.Movie
                .Include(m => m.genre)
                .Where(m => m.MovieName != null && m.MovieName.Contains(query))
                .ToListAsync();

            return View("Index", result); // Dùng lại view hiển thị danh sách phim
        }

        [HttpGet]
        public async Task<IActionResult> Search1(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                // Nếu không nhập gì thì trả lại toàn bộ danh sách
                var allMovies = await _context.Movie.Include(m => m.genre).ToListAsync();
                return View("Index", allMovies);
            }

            var result = await _context.Movie
                .Include(m => m.genre)
                .Where(m => m.MovieName != null && m.MovieName.Contains(query))
                .ToListAsync();

            return View("IndexAdmin", result); // Dùng lại view hiển thị danh sách phim
        }

        // GET: All Movies
        public async Task<IActionResult> Index()
        {
            var ckContext = _context.Movie
                .Include(m => m.genre);

            return View(await ckContext.ToListAsync());
        }
        public async Task<IActionResult> IndexAdmin()
        {
            var ckContext = _context.Movie
                .Include(m => m.genre);

            return View(await ckContext.ToListAsync());
        }
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }
        public async Task<IActionResult> DetailsAdmin(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View("DetailAdmin", movie);
        }
        // GET: Movies/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,MovieName,Capacity,Status,MovieImage,CreateAt,GenreId,Descripton,MovieImage2,Director,Video")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                movie.CreateAt = DateTime.UtcNow;

                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexAdmin));
            }
            ViewData["GenreId"] = new SelectList(_context.Set<Genre>(), "Id", "Name", movie.GenreId);
            return View( movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Set<Genre>(), "Id", "Name", movie.GenreId);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieName,Capacity,Status,MovieImage,CreateAt,GenreId,Descripton,MovieImage2,Director,Video")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("IndexAdmin");
            }
            ViewData["GenreId"] = new SelectList(_context.Set<Genre>(), "Id", "Name", movie.GenreId);
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("IndexAdmin");
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
        public IActionResult GetTicket(int id)
        {
            // Lấy danh sách lịch chiếu theo MovieId
            var showtimes = _context.Showtime
                .Where(s => s.MovieId == id)
                .ToList();

            // Truyền dữ liệu showtimes sang view
            return View("ChonShowtime", showtimes); // View tên khác tùy bạn đặt
        }


    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ck.Data;
using ck.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace ck.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ckContext _context;

        public TicketsController(ckContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var ckContext = _context.Ticket
                .Include(t => t.Seat)
                .Include(t => t.Showtime)
                .ThenInclude(s => s.Movie)
                .Include(t => t.User);
            return View(await ckContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Seat)
                .Include(t => t.Showtime)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id");
            ViewData["ShowtimeId"] = new SelectList(_context.Showtime, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SeatId,ShowtimeId,UserId,BookingDate,IsPaid,Price")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            ViewData["ShowtimeId"] = new SelectList(_context.Showtime, "Id", "Id", ticket.ShowtimeId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            ViewData["ShowtimeId"] = new SelectList(_context.Showtime, "Id", "Id", ticket.ShowtimeId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SeatId,ShowtimeId,UserId,BookingDate,IsPaid,Price")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            ViewData["ShowtimeId"] = new SelectList(_context.Showtime, "Id", "Id", ticket.ShowtimeId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Seat)
                .Include(t => t.Showtime)
                .ThenInclude(s => s.Movie) // nếu có quan hệ với phim
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket != null)
            {
                // cập nhật lại ghế nếu cần
                var seat = await _context.Seat.FindAsync(ticket.SeatId);
                if (seat != null)
                {
                    seat.IsAvailable = true;
                }

                _context.Ticket.Remove(ticket);
                await _context.SaveChangesAsync();
            }

            // nếu đang ở trang MyTickets thì quay về đó
            if (Request.Headers["Referer"].ToString().Contains("MyTickets"))
                return RedirectToAction(nameof(MyTickets));

            return RedirectToAction("Index","Home");
        }



        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }
        [Authorize]
        public async Task<IActionResult> Payment(string ticketIds)
        {
            if (string.IsNullOrEmpty(ticketIds))
                return BadRequest("Không có vé nào để thanh toán.");

            var ids = ticketIds.Split(',').Select(id => int.Parse(id)).ToList();

            var tickets = await _context.Ticket
                .Include(t => t.Seat)
                .Include(t => t.Showtime)
                    .ThenInclude(s => s.Movie) // Thêm dòng này để tải thông tin Movie
                .Include(t => t.User)
                .Where(t => ids.Contains(t.Id))
                .ToListAsync();

            if (!tickets.Any())
                return NotFound("Không tìm thấy vé nào.");

            return View(tickets); // Tìm view tại: Views/Tickets/Payment.cshtml
        }
        [HttpPost]
        [HttpPost]
        public async Task<IActionResult> ConfirmPayment(List<int> ticketIds)
        {
            if (ticketIds == null || !ticketIds.Any())
            {
                return BadRequest("No tickets selected.");
            }

            foreach (var ticketId in ticketIds)
            {
                var ticket = await _context.Ticket.FindAsync(ticketId);
                if (ticket != null)
                {
                    ticket.IsPaid = true;
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home"); // hoặc view khác phù hợp
        }

        [Authorize]
        public async Task<IActionResult> MyTickets()
        {
            // Lấy ID của người dùng hiện tại từ Claims
            var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            if (userIdClaim == null)
            {
                return Unauthorized(); // nếu chưa đăng nhập
            }

            int userId = int.Parse(userIdClaim.Value);

            // Lấy danh sách vé của người dùng hiện tại
            var myTickets = await _context.Ticket
                .Include(t => t.Seat)
                .Include(t => t.Showtime)
                 .Include(s => s.Showtime.Movie) // nếu có quan hệ với phim
                .Where(t => t.UserId == userId)
                .ToListAsync();

            return View(myTickets); // Trả về view MyTickets.cshtml
        }
    }
}

Views/Shared/Moviedetailslayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Movie Theme</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/font-awesome.min.css" rel="stylesheet">
	<link href="/css/global.css" rel="stylesheet">
	<link href="/css/index.css" rel="stylesheet">
	<link href="/css/thanhtoan.css" rel="stylesheet">
	<link href="/css/tickets.css" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Platypi:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
	<script src="/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/script.js"></script>
</head>
<body>
	@using Microsoft.AspNetCore.Http
	@inject IHttpContextAccessor HttpContextAccessor

	@{
		var username = Context.Session.GetString("Username");
		var name = Context.Session.GetString("Name");
		var role = Context.Session.GetString("Role"); 
		var userId = Context.Session.GetString("UserId");

	}
	<div class="main_o main">
		<div class="main_o1 bg_back">
			<section id="header">
				<nav class="navbar navbar-expand-md navbar-light px_4" id="navbar_sticky">
					<div class="container-fluid">
						<a class="navbar-brand  p-0 fw-bold text-white" asp-controller="Home" asp-action="Index"><i class="fa fa-modx col_oran"></i> Movie Theme </a>
						<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav mb-0 ms-auto">

								<li class="nav-item">
									<a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
								</li>

								<li class="nav-item">
									<a class="nav-link" asp-controller="Pages" asp-action="About">About Us</a>
								</li>

								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle active" asp-controller="Movies" asp-action="Index" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										Movies
									</a>
									<ul class="dropdown-menu drop_1" aria-labelledby="navbarDropdown">
										<li><a class="dropdown-item" asp-controller="Movies" asp-action="Index"><i class="fa fa-chevron-right font_12 me-1"></i> Movies</a></li>
										@await Component.InvokeAsync("NavBar")
									</ul>
								</li>
								<li class="nav-item">
									<a class="nav-link" asp-controller="Pages" asp-action="Index">Faqs</a>
								</li>

								<li class="nav-item">
									<a class="nav-link" asp-controller="Pages" asp-action="Contactus">Contact Us</a>
								</li>
								@if (!string.IsNullOrEmpty(username))
								{
									<li class="nav-item">
										<a class="nav-link" asp-controller="Tickets" asp-action="MyTickets">My Tickets</a>
									</li>
								}
								@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
								{
									<li class="nav-item">
										<a class="nav-link" asp-controller="Admin" asp-action="Index">Admin</a>
									</li>
								}
							</ul>
							<ul class="navbar-nav mb-0 ms-auto">
								<li class="nav-item">
									<a class="nav-link fs-5 drop_icon" data-bs-target="#exampleModal2" data-bs-toggle="modal" href="#"><i class="fa fa-search"></i></a>
								</li>
								<!--Login-->
								<li class="nav-item dropdown">
									<a class="nav-link fs-5 drop_icon dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
										<i class="fa fa-user"></i>
									</a>
									<ul class="dropdown-menu dropdown-menu-end">
										@if (!string.IsNullOrEmpty(username))
										{
											<li><a class="dropdown-item" href="/Users/Profile">@username</a></li>
											<li><a class="dropdown-item text-danger" href="/Users/Logout">Logout</a></li>
										}
										else
										{
											<li><a class="dropdown-item" href="/Users/Login">Login</a></li>
											<li><a class="dropdown-item" href="/Users/Register">Register</a></li>
										}
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</section>
			<section id="center" class="centre_o  pt-5 pb-5">
				<div class="container-xl">
					<div class="row centre_o1 text-center">
						<div class="col-md-12">
							<h1 class="text-white font_60">Details</h1>
							<h5 class="mb-0 mt-3 fw-normal col_oran">
								<a class="text-light" asp-controller="Home" asp-action="Index">Home</a>
								<span class="mx-2 text-muted">/</span> Movies
							</h5>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>

	<div class="border_dashed">
	</div>

	<section id="trend" class="p_3">
		<div class="container-xl">
			@RenderBody()
		</div>
	</section>
	<hr>
	@await Component.InvokeAsync("Movielikethis", new { genreId = Model.GenreId, excludeMovieId = Model.Id })
	</hr>
	<!--search-->
	<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" style="display: none; top:0;" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content bg-transparent border-0">
				<div class="modal-header border-0">
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></button>
				</div>
				<div class="modal-body p-0">
					<div class="search_1">
						<form asp-controller="Movies" asp-action="Search" method="get">
							<div class="input-group">
								<input type="text" name="query" class="form-control bg-white border-0" placeholder="Search...">
								<span class="input-group-btn">
									<button class="btn btn-primary bg_oran border_1 rounded-0 p-3 px-4" type="submit">
										<i class="fa fa-search"></i>
									</button>
								</span>
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>
	<div class="border_dashed">
	</div>
	<!--footer-->
	<section id="footer" class="p_3 bg-black">
		<div class="container-xl">
			<div class="footer_1 row pb-4">
				<div class="col-md-3">
					<div class="footer_1l">
						<h4 class="mb-0"><a class="fw-bold text-white" href="index.html"><i class="fa fa-modx col_oran"></i> Movie Theme </a></h4>
					</div>
				</div>
				<div class="col-md-9">
					<div class="footer_1r text-end">
						<ul class="mb-0">
							<li class="d-inline-block"><a class="social_icon" href="https://x.com/home"> <i class="fa fa-twitter"></i></a></li>
							<li class="d-inline-block"><a class="social_icon" href="https://facebook.com"> <i class="fa fa-facebook"></i></a></li>
							<li class="d-inline-block"><a class="social_icon" href="https://www.instagram.com/"> <i class="fa fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="footer_2 row mt-4">
				
				<div class="col-md-3">
					<div class="footer_2i">
						<!--tagfooter-->
						<h5 class="col_oran mb-4">Movies</h5>
						<div class="row footer_1ism">
							@await Component.InvokeAsync("NavBar")
						</div>

						<!--tagfooter-->
					</div>
				</div>

				<div class="col-md-3">
					<div class="footer_2i">
						<h5 class="col_oran mb-4">Links</h5>
						<div class="row footer_1ism">
							<h6 class="fw-normal col-md-12 col-6"><a class="text-white-50 a_tag" asp-controller="Pages" asp-action="About"> About Us</a></h6>
							<h6 class="fw-normal mt-2 col-md-12 col-6"><a class="text-white-50 a_tag" href="/Users/Profile"> My account</a></h6>
							<h6 class="fw-normal mt-2 col-md-12 col-6 mb-0"><a class="text-white-50 a_tag" asp-controller="Pages" asp-action="Contactus"> Contact Us</a></h6>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="/js/common.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MovieCardPartial.cshtml
@model ck.Models.Movie

<div class="col-md-3 col-sm-6">
    <div class="trend_2i position-relative">
        <div class="trend_2i1">
            <img src="@Model.MovieImage" class="w-100" alt="@Model.MovieName">
        </div>
        <div class="trend_2i2 bg_back position-absolute w-100 h-100 top-0 px-4">
            <h6 class="font_14 text-light">@Model.genre.Name / @Model.Capacity Minute</h6>
            <h5>
                <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">@Model.MovieName</a>
            </h5>
            <h6 class="mb-0 mt-3">
                <a class="button_1 p-2 px-3 font_14"
                   asp-controller="Showtimes"
                   asp-action="GetTicket"
                   asp-route-movieId="@Model.Id">
                    Get Ticket
                </a>
            </h6>
        </div>
    </div>
</div>